name:                aoc
version:             0.1.0.0
github:              "github.com/advait/aoc-reasonml"
license:             BSD3
author:              "Advait Shinde"
maintainer:          "example@example.com"
copyright:           "2019 Advait Shinde"

extra-source-files:
  - README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/advait/aoc-reasonml/README.md>

dependencies:
  - base >= 4.7 && < 5

executables:
  advent1:
    main:                Advent1.hs
    source-dirs:         app/A1
    ghc-options:
      - -main-is A1.Advent1
    dependencies:
      - containers
  advent9:
    main:                Advent9.hs
    source-dirs:         app/A9
    ghc-options:
      - -main-is A9.Advent9
    dependencies:
      - containers
      - deque
  advent12:
    main:                Advent12.hs
    source-dirs:         app/A12
    ghc-options:
      - -main-is A12.Advent12
    dependencies:
      - containers
  advent13:
    main:                Advent13.hs
    source-dirs:         app/A13
    ghc-options:
      - -main-is A13.Advent13
    dependencies:
      - containers
  advent14:
    main:                Advent14.hs
    source-dirs:         app/A14
    ghc-options:
      - -main-is A14.Advent14
    dependencies:
      - containers
  advent15:
    main:                Advent15.hs
    source-dirs:         app/A15
    ghc-options:
      - -main-is A15.Advent15
    dependencies:
      - containers
  advent16:
    main:                Advent16.hs
    source-dirs:         app/A16
    ghc-options:
      - -main-is A16.Advent16
    dependencies:
      - containers
      - mtl

tests:
  aoc-test:
    defaults: hspec/hspec@master
    source-dirs:
      - app
      - test
    main: Main.hs
    dependencies:
      - containers
      - deque
      - mtl
