name:                aoc
version:             0.1.0.0
github:              "github.com/advait/aoc-reasonml"
license:             BSD3
author:              "Advait Shinde"
maintainer:          "example@example.com"
copyright:           "2019 Advait Shinde"

extra-source-files:
  - README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/advait/aoc-reasonml/README.md>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: app
  dependencies:
    - containers
    - deque
    - QuickCheck

executables:
  advent1:
    main:                Advent1.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fwarn-incomplete-patterns
      - -main-is Advent1
    dependencies:
      - containers
      - deque
      - QuickCheck
  advent9:
    main:                Advent9.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fwarn-incomplete-patterns
      - -main-is Advent9
    dependencies:
      - containers
      - deque
      - QuickCheck

tests:
  aoc-test:
    defaults: hspec/hspec@master
    dependencies:
      - aoc
      - containers
      - deque
